#!/usr/bin/env python3
"""
First-run authentication bootstrap for the REST API / Web UI.

The API refuses to start without DCIM_AUTH_SECRET, and login needs at least one
user. Both live in ./auth.env (gitignored), which run.sh / run.bat load before
launching. This script CREATES that file on first run so the launchers can set
up authentication automatically — no manual `cp auth.env.example auth.env` +
`python -m api.auth set-password` dance.

Behaviour (idempotent):
  * auth.env already has a non-empty DCIM_AUTH_SECRET -> do nothing, exit 0.
  * otherwise generate a stable JWT secret + an admin password hash and write
    auth.env (single-quoted values; the PBKDF2 hash contains '$').

Password source, in order:
  1. $DCIM_BOOTSTRAP_PASSWORD     (non-interactive / CI)
  2. interactive getpass prompt   (a real console)
  3. random, printed once         (no TTY available)

Stdlib only — runs even before project dependencies are installed.
"""
from __future__ import annotations

import hashlib
import os
import secrets
import sys

_ROOT = os.path.dirname(os.path.abspath(__file__))
AUTH_ENV = os.path.join(_ROOT, "auth.env")

# Must match api.auth.verify_hash exactly.
_PBKDF2_ROUNDS = 200_000
_PBKDF2_PREFIX = "pbkdf2_sha256"


def hash_password(plain: str) -> str:
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", plain.encode("utf-8"), salt, _PBKDF2_ROUNDS)
    return f"{_PBKDF2_PREFIX}${_PBKDF2_ROUNDS}${salt.hex()}${digest.hex()}"


def _existing_secret() -> str:
    """Return a non-empty DCIM_AUTH_SECRET already on disk, else ''."""
    if not os.path.isfile(AUTH_ENV):
        return ""
    try:
        with open(AUTH_ENV, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line.startswith("#") or "=" not in line:
                    continue
                key, _, val = line.partition("=")
                if key.strip() == "DCIM_AUTH_SECRET":
                    return val.strip().strip("'\"")
    except OSError:
        pass
    return ""


def _get_password() -> tuple[str, bool]:
    """Return (password, was_generated)."""
    env_pw = os.environ.get("DCIM_BOOTSTRAP_PASSWORD", "")
    if env_pw:
        if len(env_pw) < 8:
            print("ERROR: DCIM_BOOTSTRAP_PASSWORD must be at least 8 characters.", file=sys.stderr)
            raise SystemExit(1)
        return env_pw, False

    if sys.stdin and sys.stdin.isatty():
        import getpass
        while True:
            pw1 = getpass.getpass("Create admin password (min 8 chars): ")
            if len(pw1) < 8:
                print("Too short.")
                continue
            pw2 = getpass.getpass("Confirm password: ")
            if pw1 != pw2:
                print("Passwords do not match. Try again.")
                continue
            return pw1, False

    # No TTY (double-clicked / piped) -> generate a random one and show it once.
    return secrets.token_urlsafe(12), True


def _wants_new_credentials() -> bool:
    """Ask whether to replace existing auth.env. Default = keep."""
    # Explicit override for non-interactive use.
    force = os.environ.get("DCIM_AUTH_RECREATE", "").strip().lower()
    if force in ("1", "true", "yes"):
        return True
    if force in ("0", "false", "no"):
        return False
    if not (sys.stdin and sys.stdin.isatty()):
        return False  # no TTY -> never clobber working credentials
    print(f"Authentication already configured ({AUTH_ENV}).")
    ans = input("Keep existing credentials or create new? [K]eep / [n]ew: ").strip().lower()
    return ans in ("n", "new")


def main() -> int:
    if _existing_secret():
        if not _wants_new_credentials():
            print("Using existing auth.env.")
            return 0
        print("Replacing auth.env with new credentials ...")

    username = os.environ.get("DCIM_AUTH_USERNAME", "admin")
    if not os.path.isfile(AUTH_ENV):
        print("No authentication configured — creating auth.env ...")
    password, generated = _get_password()

    secret = secrets.token_urlsafe(48)
    pw_hash = hash_password(password)

    lines = [
        "# Auto-generated by bootstrap_auth.py — do not commit (gitignored).",
        "# Reuse the SAME DCIM_AUTH_SECRET across restarts or logins are invalidated.",
        "# Values are single-quoted: the PBKDF2 hash contains '$' separators.",
        f"DCIM_AUTH_SECRET='{secret}'",
        f"DCIM_AUTH_PASSWORD_HASH='{pw_hash}'",
    ]
    if username != "admin":
        lines.append(f"DCIM_AUTH_USERNAME='{username}'")
    lines.append("")

    tmp = AUTH_ENV + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    os.replace(tmp, AUTH_ENV)
    try:
        os.chmod(AUTH_ENV, 0o600)  # no-op semantics on Windows, real on POSIX
    except OSError:
        pass

    print(f"Wrote {AUTH_ENV}")
    print(f"  Web UI / REST API login -> username: {username}")
    if generated:
        print(f"  GENERATED PASSWORD: {password}")
        print("  ^ Save this now — it is not stored anywhere in plain text.")
    print("Change later with: python -m api.auth set-password  (then update auth.env)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())