-- Rack PDU (CDU) SNMP templates -> fac_CDUTemplate.
-- Generated by tools/export_to_opendcim.py.
-- openDCIM's REST API cannot write this table: the OID columns live on
-- CDUTemplate, and PUT /api/v1/devicetemplate copies only DeviceTemplate's
-- own properties. Without these the Status column on a CDU's Power
-- Connections panel stays 'err' forever, and the PDU is never polled for
-- wattage (UpdateStats joins on Managed=true).
--
-- The OIDs are the SIMULATOR's private PDU table, not a real PDU's MIB.
-- Replace them per SKU before pointing openDCIM at real gear.

-- APC AP8886: 42 outlets, 400 V / 32 A nameplate, 231 V at the outlet
INSERT IGNORE INTO fac_CDUTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='APC AP8886' AND dt.DeviceType='CDU';
UPDATE fac_CDUTemplate ct JOIN fac_DeviceTemplate dt ON dt.TemplateID=ct.TemplateID
  SET ct.Managed=1, ct.ATS=0, ct.SNMPVersion='2c',
      ct.VersionOID='1.3.6.1.2.1.1.1.0',
      ct.OutletNameOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletDescOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletCountOID='',
      ct.OutletStatusOID='1.3.6.1.4.1.99999.5.20.1.3',
      ct.OutletStatusOn='1',
      ct.Multiplier='0.1',
      ct.OID1='1.3.6.1.4.1.318.1.1.26.4.3.1.5.1', ct.OID2='', ct.OID3='',
      ct.ATSStatusOID='',
      ct.ATSDesiredResult='',
      ct.ProcessingProfile='SingleOIDWatts',
      ct.Voltage=400, ct.Amperage=32,
      ct.NumOutlets=42
  WHERE dt.Model='APC AP8886' AND dt.DeviceType='CDU';

-- APC AP8941: 24 outlets, 208 V / 30 A nameplate, 208 V at the outlet
INSERT IGNORE INTO fac_CDUTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='APC AP8941' AND dt.DeviceType='CDU';
UPDATE fac_CDUTemplate ct JOIN fac_DeviceTemplate dt ON dt.TemplateID=ct.TemplateID
  SET ct.Managed=1, ct.ATS=0, ct.SNMPVersion='2c',
      ct.VersionOID='1.3.6.1.2.1.1.1.0',
      ct.OutletNameOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletDescOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletCountOID='',
      ct.OutletStatusOID='1.3.6.1.4.1.99999.5.20.1.3',
      ct.OutletStatusOn='1',
      ct.Multiplier='0.1',
      ct.OID1='1.3.6.1.4.1.318.1.1.26.4.3.1.5.1', ct.OID2='', ct.OID3='',
      ct.ATSStatusOID='',
      ct.ATSDesiredResult='',
      ct.ProcessingProfile='SingleOIDWatts',
      ct.Voltage=208, ct.Amperage=30,
      ct.NumOutlets=24
  WHERE dt.Model='APC AP8941' AND dt.DeviceType='CDU';

-- Raritan PX2-5170CR: 30 outlets, 208 V / 30 A nameplate, 208 V at the outlet
INSERT IGNORE INTO fac_CDUTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='Raritan PX2-5170CR' AND dt.DeviceType='CDU';
UPDATE fac_CDUTemplate ct JOIN fac_DeviceTemplate dt ON dt.TemplateID=ct.TemplateID
  SET ct.Managed=1, ct.ATS=0, ct.SNMPVersion='2c',
      ct.VersionOID='1.3.6.1.2.1.1.1.0',
      ct.OutletNameOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletDescOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletCountOID='',
      ct.OutletStatusOID='1.3.6.1.4.1.99999.5.20.1.3',
      ct.OutletStatusOn='1',
      ct.Multiplier='1',
      ct.OID1='1.3.6.1.4.1.13742.6.5.2.3.1.4.1.1.5', ct.OID2='', ct.OID3='',
      ct.ATSStatusOID='',
      ct.ATSDesiredResult='',
      ct.ProcessingProfile='SingleOIDWatts',
      ct.Voltage=208, ct.Amperage=30,
      ct.NumOutlets=30
  WHERE dt.Model='Raritan PX2-5170CR' AND dt.DeviceType='CDU';

-- Enroll the rack PDUs in status polling.
-- NetworkCapacityReportOptIn='OptIn' makes devices.php return an empty
-- status array for anything without this tag, before any SNMP happens.
-- Both device types that HAVE a Status column are enrolled: CDU (outlet
-- state, CDUInfo::getPortStatus) and Switch (port link state,
-- SwitchInfo::getPortStatus). No other type renders one, so tagging
-- anything else would buy polling load and no display.
INSERT IGNORE INTO fac_Tags (Name) VALUES ('Poll');
INSERT IGNORE INTO fac_DeviceTags (DeviceID, TagID)
  SELECT d.DeviceID, t.TagID FROM fac_Device d, fac_Tags t
  WHERE d.DeviceType IN ('CDU','Switch') AND t.Name='Poll';

-- Rack PDU outlet counts, from the SKU catalog.
-- openDCIM materialises one power port per PowerSupplyCount and a cord is
-- stored as load-port -> (CDU, outlet), so a strip short of ports simply has
-- nowhere to land the cords above the count, and its panel renders short.
-- GROW ONLY — see outlet_count_sql() in tools/export_to_opendcim.py.
UPDATE fac_Device d JOIN fac_DeviceTemplate dt ON dt.TemplateID=d.TemplateID
  SET d.PowerSupplyCount = GREATEST(d.PowerSupplyCount, CASE
      WHEN dt.Model='APC AP8886' THEN 42
      WHEN dt.Model='APC AP8941' THEN 24
      WHEN dt.Model='Raritan PX2-5170CR' THEN 30
      ELSE d.PowerSupplyCount END)
  WHERE d.DeviceType='CDU';

-- Materialise the ports the count now promises. openDCIM's own createPorts()
-- cannot be used: it re-INSERTs from port 1 and dies on the duplicate.
INSERT IGNORE INTO fac_PowerPorts (DeviceID, PortNumber, Label,
                                   ConnectedDeviceID, ConnectedPort, Notes)
  SELECT d.DeviceID, n.n, CONCAT('Power Connection ', n.n), NULL, NULL, ''
  FROM fac_Device d JOIN (
         SELECT a.N + b.N * 10 + 1 AS n FROM
           (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL
            SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
            SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
            SELECT 9) a,
           (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL
            SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
            SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
            SELECT 9) b
       ) n ON n.n <= d.PowerSupplyCount
  WHERE d.DeviceType='CDU';

-- Rack PDU outlet labels: name every receptacle after its number.
-- Label ONLY — never touches ConnectedDeviceID, so no cord can be lost.
-- Do NOT do this through POST /api/v1/powerport/{id}: that route builds a
-- fresh PowerPorts object from the posted fields, so omitting the
-- connection clears it. See outlet_label_sql() in this file.
UPDATE fac_PowerPorts pp JOIN fac_Device d ON d.DeviceID=pp.DeviceID
  SET pp.Label = CONCAT('Outlet ', pp.PortNumber)
  WHERE d.DeviceType='CDU';

-- Environmental sensor SNMP templates -> fac_SensorTemplate.
-- openDCIM auto-creates a BLANK shadow row beside every Sensor device
-- template (DeviceTemplate.class.php) and no REST route can fill it, so
-- until this runs poll_temperature_sensors.php reads a template with empty
-- OIDs, skips the SNMP and writes Temperature=0 -- which renders as a real
-- 0.00 reading in the UI. See SENSOR_SIM_TEMPLATE in
-- tools/export_to_opendcim.py for why each OID is the one it is.

-- Raritan DPX2-CC2 x15: inlet temperature only (no hygrometer on this head)
INSERT IGNORE INTO fac_SensorTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='Raritan DPX2-CC2' AND dt.DeviceType='Sensor';
UPDATE fac_SensorTemplate st JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  SET st.TemperatureOID='1.3.6.1.4.1.13742.6.5.5.3.1.4.1.2',
      st.HumidityOID='',
      st.TempMultiplier=0.1,
      st.HumidityMultiplier=1.0,
      st.mUnits='metric'
  WHERE dt.Model='Raritan DPX2-CC2' AND dt.DeviceType='Sensor';

-- Raritan DPX2-T3H1 x4: inlet temperature, relative humidity
INSERT IGNORE INTO fac_SensorTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='Raritan DPX2-T3H1' AND dt.DeviceType='Sensor';
UPDATE fac_SensorTemplate st JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  SET st.TemperatureOID='1.3.6.1.4.1.13742.6.5.5.3.1.4.1.1',
      st.HumidityOID='1.3.6.1.4.1.13742.6.5.5.3.1.4.1.4',
      st.TempMultiplier=0.1,
      st.HumidityMultiplier=0.1,
      st.mUnits='metric'
  WHERE dt.Model='Raritan DPX2-T3H1' AND dt.DeviceType='Sensor';

-- Chiller-plant header instruments: REMOVE the auto-created shadow row.
-- These are BMS points, not room environmentals -- a thermowell in a
-- water header and a magnetic flow meter on the main. openDCIM stores
-- only air temperature and RH, and DataCenter::AvgTemp averages every
-- non-backside sensor in the datacenter with no room filter, so a 7 C
-- chilled-water supply and a 35 C condenser return would both land in
-- the hall's average and in TemperatureRed. With no template row
-- UpdateSensorsFilter's GetTemplate() returns false and skips them, so
-- they stay inventoried assets and record no reading at all.
-- Guarded on both OIDs being empty: this never removes a row that
-- someone has deliberately filled in.
DELETE st FROM fac_SensorTemplate st
  JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  WHERE dt.Model='Plant CHW Flow Meter' AND dt.DeviceType='Sensor'
    AND st.TemperatureOID='' AND st.HumidityOID='';
DELETE st FROM fac_SensorTemplate st
  JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  WHERE dt.Model='Plant CHW Return Temp' AND dt.DeviceType='Sensor'
    AND st.TemperatureOID='' AND st.HumidityOID='';
DELETE st FROM fac_SensorTemplate st
  JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  WHERE dt.Model='Plant CHW Supply Temp' AND dt.DeviceType='Sensor'
    AND st.TemperatureOID='' AND st.HumidityOID='';
DELETE st FROM fac_SensorTemplate st
  JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  WHERE dt.Model='Plant CT Basin Temp' AND dt.DeviceType='Sensor'
    AND st.TemperatureOID='' AND st.HumidityOID='';
DELETE st FROM fac_SensorTemplate st
  JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  WHERE dt.Model='Plant CW Return Temp' AND dt.DeviceType='Sensor'
    AND st.TemperatureOID='' AND st.HumidityOID='';
DELETE st FROM fac_SensorTemplate st
  JOIN fac_DeviceTemplate dt ON dt.TemplateID=st.TemplateID
  WHERE dt.Model='Plant CW Supply Temp' AND dt.DeviceType='Sensor'
    AND st.TemperatureOID='' AND st.HumidityOID='';

-- Cabinet power meter thresholds (percent of the cabinet's MaxKW).
-- Both cabinet percentages are CLAMPED to 100 before the colour test, so a
-- threshold >= 100 can never fire. Raising PowerRed above 100 does not make
-- the meter quieter, it makes every rack green. Read the comment on
-- CABINET_POWER_YELLOW_PCT in tools/export_to_opendcim.py before changing.
UPDATE fac_Config SET Value=85 WHERE Parameter='PowerYellow';
UPDATE fac_Config SET Value=100 WHERE Parameter='PowerRed';

