-- Rack PDU (CDU) SNMP templates -> fac_CDUTemplate.
-- Generated by tools/export_to_opendcim.py.
-- openDCIM's REST API cannot write this table: the OID columns live on
-- CDUTemplate, and PUT /api/v1/devicetemplate copies only DeviceTemplate's
-- own properties. Without these the Status column on a CDU's Power
-- Connections panel stays 'err' forever, and the PDU is never polled for
-- wattage (UpdateStats joins on Managed=true).
--
-- The OIDs are the SIMULATOR's private PDU table, not a real PDU's MIB.
-- Replace them per SKU before pointing openDCIM at real gear.

-- APC AP8886: 42 outlets, 400 V / 32 A nameplate, 231 V at the outlet
INSERT IGNORE INTO fac_CDUTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='APC AP8886' AND dt.DeviceType='CDU';
UPDATE fac_CDUTemplate ct JOIN fac_DeviceTemplate dt ON dt.TemplateID=ct.TemplateID
  SET ct.Managed=1, ct.ATS=0, ct.SNMPVersion='2c',
      ct.VersionOID='',
      ct.OutletNameOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletDescOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletCountOID='',
      ct.OutletStatusOID='1.3.6.1.4.1.99999.5.20.1.3',
      ct.OutletStatusOn='1',
      ct.Multiplier='1',
      ct.OID1='1.3.6.1.4.1.99999.5.11.0', ct.OID2='', ct.OID3='',
      ct.ATSStatusOID='',
      ct.ATSDesiredResult='',
      ct.ProcessingProfile='SingleOIDWatts',
      ct.Voltage=400, ct.Amperage=32,
      ct.NumOutlets=42
  WHERE dt.Model='APC AP8886' AND dt.DeviceType='CDU';

-- APC AP8941: 24 outlets, 208 V / 30 A nameplate, 208 V at the outlet
INSERT IGNORE INTO fac_CDUTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='APC AP8941' AND dt.DeviceType='CDU';
UPDATE fac_CDUTemplate ct JOIN fac_DeviceTemplate dt ON dt.TemplateID=ct.TemplateID
  SET ct.Managed=1, ct.ATS=0, ct.SNMPVersion='2c',
      ct.VersionOID='',
      ct.OutletNameOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletDescOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletCountOID='',
      ct.OutletStatusOID='1.3.6.1.4.1.99999.5.20.1.3',
      ct.OutletStatusOn='1',
      ct.Multiplier='1',
      ct.OID1='1.3.6.1.4.1.99999.5.11.0', ct.OID2='', ct.OID3='',
      ct.ATSStatusOID='',
      ct.ATSDesiredResult='',
      ct.ProcessingProfile='SingleOIDWatts',
      ct.Voltage=208, ct.Amperage=30,
      ct.NumOutlets=24
  WHERE dt.Model='APC AP8941' AND dt.DeviceType='CDU';

-- Raritan PX2-5170CR: 30 outlets, 208 V / 30 A nameplate, 208 V at the outlet
INSERT IGNORE INTO fac_CDUTemplate (TemplateID, ManufacturerID, Model)
  SELECT dt.TemplateID, dt.ManufacturerID, dt.Model FROM fac_DeviceTemplate dt
  WHERE dt.Model='Raritan PX2-5170CR' AND dt.DeviceType='CDU';
UPDATE fac_CDUTemplate ct JOIN fac_DeviceTemplate dt ON dt.TemplateID=ct.TemplateID
  SET ct.Managed=1, ct.ATS=0, ct.SNMPVersion='2c',
      ct.VersionOID='',
      ct.OutletNameOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletDescOID='1.3.6.1.4.1.99999.5.20.1.2',
      ct.OutletCountOID='',
      ct.OutletStatusOID='1.3.6.1.4.1.99999.5.20.1.3',
      ct.OutletStatusOn='1',
      ct.Multiplier='1',
      ct.OID1='1.3.6.1.4.1.99999.5.11.0', ct.OID2='', ct.OID3='',
      ct.ATSStatusOID='',
      ct.ATSDesiredResult='',
      ct.ProcessingProfile='SingleOIDWatts',
      ct.Voltage=208, ct.Amperage=30,
      ct.NumOutlets=30
  WHERE dt.Model='Raritan PX2-5170CR' AND dt.DeviceType='CDU';

-- Enroll the rack PDUs in status polling.
-- NetworkCapacityReportOptIn='OptIn' makes devices.php return an empty
-- status array for anything without this tag, before any SNMP happens.
-- Switches have a Status column too; add DeviceType='Switch' below to
-- enroll those as well.
INSERT IGNORE INTO fac_Tags (Name) VALUES ('Poll');
INSERT IGNORE INTO fac_DeviceTags (DeviceID, TagID)
  SELECT d.DeviceID, t.TagID FROM fac_Device d, fac_Tags t
  WHERE d.DeviceType='CDU' AND t.Name='Poll';

-- Rack PDU outlet counts, from the SKU catalog.
-- openDCIM materialises one power port per PowerSupplyCount and a cord is
-- stored as load-port -> (CDU, outlet), so a strip short of ports simply has
-- nowhere to land the cords above the count, and its panel renders short.
-- GROW ONLY — see outlet_count_sql() in tools/export_to_opendcim.py.
UPDATE fac_Device d JOIN fac_DeviceTemplate dt ON dt.TemplateID=d.TemplateID
  SET d.PowerSupplyCount = GREATEST(d.PowerSupplyCount, CASE
      WHEN dt.Model='APC AP8886' THEN 42
      WHEN dt.Model='APC AP8941' THEN 24
      WHEN dt.Model='Raritan PX2-5170CR' THEN 30
      ELSE d.PowerSupplyCount END)
  WHERE d.DeviceType='CDU';

-- Materialise the ports the count now promises. openDCIM's own createPorts()
-- cannot be used: it re-INSERTs from port 1 and dies on the duplicate.
INSERT IGNORE INTO fac_PowerPorts (DeviceID, PortNumber, Label,
                                   ConnectedDeviceID, ConnectedPort, Notes)
  SELECT d.DeviceID, n.n, CONCAT('Power Connection ', n.n), NULL, NULL, ''
  FROM fac_Device d JOIN (
         SELECT a.N + b.N * 10 + 1 AS n FROM
           (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL
            SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
            SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
            SELECT 9) a,
           (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL
            SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
            SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
            SELECT 9) b
       ) n ON n.n <= d.PowerSupplyCount
  WHERE d.DeviceType='CDU';

