-- Rack PDU -> RPP breaker assignments.
-- Generated by tools/export_to_opendcim.py. A feeds odd poles, B feeds even.
-- Positions are an assigned scheme: the simulator models no breaker numbers.
--
-- BreakerSize is the POLE COUNT (1/2/3), NOT the trip rating. Three places
-- read it that way: cabnavigator derives the strip's ceiling from it
-- (1 -> V/sqrt(3) single-phase, 2 -> V, 3 -> V*sqrt(3) three-phase),
-- GetAllBreakerPoles() walks 1..BreakerSize to span the schedule, and
-- UpdateStats() tests == 3. Writing the AMPERAGE here (this tool used to
-- write 32) claims a 32-pole breaker, and every single-phase strip then
-- gets costed as three-phase -- 18.4 kW of headroom on a 6.2 kW unit.
-- The trip rating belongs in InputAmperage, which is where cabnavigator
-- reads it from.

UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-CP' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-CP';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-HA-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-HA-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-HA-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HA-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HA-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HA-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HA-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '16', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HA-R2-05';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-HB-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-HB-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-HB-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HB-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HB-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HB-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HB-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '16', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC1-HB-R2-05';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-NR-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-NR-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-NR-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC1-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC1-NR-R1-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-CP' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-CP';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-HA-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-HA-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-HA-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HA-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HA-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HA-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HA-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HA-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-HB-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-HB-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-HB-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HB-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HB-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HB-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-HB-R1-04' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUA-DC2-HB-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-NR-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-NR-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-NR-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPA-DC2-NR-R2-01' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUA-DC2-NR-R1-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-CP' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-CP';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-HA-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-HA-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-HA-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HA-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HA-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HA-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HA-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '16', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HA-R2-05';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-HB-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-HB-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-HB-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HB-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HB-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HB-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HB-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '16', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC1-HB-R2-05';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-NR-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-NR-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-NR-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC1-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC1-NR-R1-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-CP' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-CP';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-HA-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-HA-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-HA-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HA-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HA-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HA-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HA-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HA-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-HB-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-HB-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-HB-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HB-R2-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '5', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HB-R2-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '10', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HB-R2-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-HB-R1-13' SET pd.PanelID = pp.PanelID, pd.PanelPole = '11', pd.BreakerSize = 3, pd.InputAmperage = 32 WHERE pd.Label = 'PDUB-DC2-HB-R2-04';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '1', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-NR-R1-01';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '2', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-NR-R1-02';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '3', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-NR-R1-03';
UPDATE fac_PowerDistribution pd JOIN fac_PowerPanel pp ON pp.PanelLabel = 'RPPB-DC2-NR-R2-02' SET pd.PanelID = pp.PanelID, pd.PanelPole = '4', pd.BreakerSize = 1, pd.InputAmperage = 30 WHERE pd.Label = 'PDUB-DC2-NR-R1-04';
