"""End-to-end pipeline smoke tests using synthetic data (no live DB).

Runs select_forecaster → compute_capacity → build_recommendations on data
generated by testdata.py, verifying that the full prediction pipeline
produces valid outputs for every target the aggregator provides.
"""
from __future__ import annotations

from datetime import date

import pandas as pd
import pytest

from app.db.testdata import generate_all_series, generate_capacity_snapshot
from app.engines.capacity import compute_capacity
from app.engines.recommendations import build_recommendations
from app.models.selection import select_forecaster

# One shared session-level run — generation is cheap but model training is not.
_SERIES = generate_all_series(n_days=365)
_SNAPSHOT = generate_capacity_snapshot()
_TODAY = date(2026, 6, 26)
_HORIZON = 90


def _sel(target: str, series: dict | None = None, horizon: int = _HORIZON):
    s = (series or _SERIES)[target]
    return select_forecaster(s, horizon)


# ── Forecaster selection ──────────────────────────────────────────────────────

class TestForecastAllTargets:
    @pytest.mark.parametrize(
        "target",
        ["cpu", "memory", "temperature", "storage", "power", "server_count"],
    )
    def test_forecaster_selected_for_365d(self, target):
        sel = _sel(target)
        assert sel is not None, f"No forecaster selected for '{target}'"
        assert len(sel.points) == _HORIZON

    @pytest.mark.parametrize(
        "target",
        ["cpu", "memory", "temperature", "storage", "power", "server_count"],
    )
    def test_prediction_intervals_are_ordered_and_nonneg(self, target):
        sel = _sel(target)
        for p in sel.points:
            assert p.lower >= 0.0, f"{target}: lower bound negative"
            assert p.lower <= p.value, f"{target}: lower > value"
            assert p.value <= p.upper, f"{target}: value > upper"

    @pytest.mark.parametrize("target", ["cpu", "memory", "storage"])
    def test_utilisation_targets_stay_under_100(self, target):
        sel = _sel(target)
        # Not a hard cap (models can overshoot), but should be reasonable
        assert all(p.upper < 120.0 for p in sel.points), \
            f"{target}: upper bound implausibly high"

    def test_xgboost_or_hw_chosen_for_365d_cpu(self):
        sel = _sel("cpu")
        assert sel.name in ("xgboost", "holt_winters"), \
            f"Expected heavy model for 365-day CPU series, got '{sel.name}'"

    def test_mae_is_recorded_for_long_series(self):
        sel = _sel("cpu")
        assert sel.mae is not None
        assert sel.mae >= 0.0

    def test_trend_fallback_for_3d_series(self, tiny_series):
        sel = _sel("cpu", series=tiny_series, horizon=2)
        assert sel is not None
        assert sel.name == "trend"

    def test_none_returned_for_single_point(self):
        s = pd.Series([42.0], index=pd.date_range("2026-01-01", periods=1, freq="D"))
        assert select_forecaster(s, 5) is None

    def test_short_series_degrades_gracefully(self, short_series):
        sel = _sel("cpu", series=short_series)
        assert sel is not None
        assert len(sel.points) == _HORIZON


# ── Temperature forecasting ───────────────────────────────────────────────────

class TestTemperatureForecasting:
    def test_temperature_values_in_celsius_range(self):
        sel = _sel("temperature")
        for p in sel.points:
            # Datacenter temps should stay between 14°C and 40°C
            assert p.lower < 45.0, "Temperature upper bound too high"

    def test_temperature_trend_is_upward(self):
        sel = _sel("temperature")
        first = sel.points[0].value
        last = sel.points[-1].value
        # 18→27°C trend — forecast should be > starting value
        assert last >= first - 3.0, "Temperature forecast dropped unexpectedly"


# ── Capacity engine ───────────────────────────────────────────────────────────

class TestCapacityWithTestData:
    def _cap(self, power_points=None):
        srv = _sel("server_count")
        return compute_capacity(
            _SNAPSHOT, srv.points, current_servers=65.0,
            power_points=power_points,
            rack_u_default=42, rack_power_capacity_w=60_000,
            horizons=[30, 60, 90], today=_TODAY,
        )

    def test_derived_forecasts_present(self):
        cap = self._cap()
        assert "rack_units" in cap.derived_forecasts
        assert "storage" in cap.derived_forecasts

    def test_server_growth_numbers_positive(self):
        cap = self._cap()
        for h in (30, 60, 90):
            growth = cap.summary.get(f"expected_server_growth_{h}d")
            if growth is not None:
                assert growth >= 0

    def test_power_headroom_computed_when_power_forecast_provided(self):
        power_sel = _sel("power")
        cap = self._cap(power_points=power_sel.points)
        h = cap.summary.get("power_headroom_pct")
        assert h is not None
        assert -200 < h < 100

    def test_exhaustion_dates_are_dates_or_none(self):
        cap = self._cap()
        s = cap.summary
        for key in ("rack_exhaustion_date", "storage_exhaustion_date"):
            val = s.get(key)
            assert val is None or isinstance(val, date), \
                f"{key} has unexpected type {type(val)}"

    def test_empty_snapshot_is_graceful(self):
        empty = {"totals": {}, "racks": []}
        srv = _sel("server_count")
        cap = compute_capacity(
            empty, srv.points, current_servers=0.0, power_points=None,
            rack_u_default=42, rack_power_capacity_w=60_000,
            horizons=[30, 60, 90], today=_TODAY,
        )
        assert cap.summary["rack_exhaustion_date"] is None


# ── Recommendations ───────────────────────────────────────────────────────────

class TestRecommendationsWithTestData:
    def _build(self, cpu_threshold=85.0, mem_threshold=85.0):
        sel_cpu = _sel("cpu")
        sel_mem = _sel("memory")
        sel_srv = _sel("server_count")
        cap = compute_capacity(
            _SNAPSHOT, sel_srv.points, current_servers=65.0, power_points=None,
            rack_u_default=42, rack_power_capacity_w=60_000,
            horizons=[30, 60, 90], today=_TODAY,
        )
        return build_recommendations(
            "global", "all", cap.summary,
            {"cpu": sel_cpu, "memory": sel_mem, "server_count": sel_srv},
            today=_TODAY, cpu_threshold=cpu_threshold, mem_threshold=mem_threshold,
            server_mape=sel_srv.mape,
        )

    def test_recommendations_are_valid_dicts(self):
        recs = self._build()
        assert isinstance(recs, list)
        for r in recs:
            assert r["severity"] in ("info", "warning", "critical")
            assert 0.0 <= r["confidence"] <= 1.0
            assert r["category"] in ("rack", "storage", "power", "cpu", "server")

    def test_cpu_recommendation_fires_when_threshold_will_be_crossed(self):
        # Manufacture a CPU series that will clearly cross 60% in 90 days
        idx = pd.date_range("2025-06-26", periods=200, freq="D")
        vals = [40.0 + i * 0.25 for i in range(200)]  # 40→90%, crosses 60% at day 80
        s = pd.Series(vals, index=idx, dtype="float64")
        sel = select_forecaster(s, 90)
        assert sel is not None
        recs = build_recommendations(
            "test", "dc1", {},
            {"cpu": sel},
            today=_TODAY, cpu_threshold=60.0, mem_threshold=85.0,
            server_mape=sel.mape,
        )
        cpu_recs = [r for r in recs if r["category"] == "cpu"]
        assert len(cpu_recs) > 0, "Expected a CPU threshold recommendation"
        assert cpu_recs[0]["predicted_date"] is not None

    def test_low_threshold_triggers_critical_severity(self):
        # Force a critical recommendation by using a threshold already breached
        idx = pd.date_range("2025-06-26", periods=100, freq="D")
        # Already at 90%, will definitely cross 85%
        vals = [88.0 + i * 0.05 for i in range(100)]
        s = pd.Series(vals, index=idx, dtype="float64")
        sel = select_forecaster(s, 90)
        assert sel is not None
        recs = build_recommendations(
            "test", "dc1", {},
            {"cpu": sel},
            today=_TODAY, cpu_threshold=85.0, mem_threshold=85.0,
            server_mape=None,
        )
        # Should fire immediately (day ~0) → critical
        cpu_recs = [r for r in recs if r["category"] == "cpu"]
        if cpu_recs:
            assert cpu_recs[0]["severity"] in ("critical", "warning")


# ── Metric-change responsiveness ──────────────────────────────────────────────

class TestPredictionRespondsToMetricChanges:
    """Verify that metric trends are reflected in forecast direction.

    This is the core ML contract: predictions must track real data changes,
    not just emit a flat baseline.
    """

    def test_rising_cpu_predicts_higher_values(self):
        idx = pd.date_range("2025-01-01", periods=90, freq="D")
        rising = pd.Series([30.0 + i * 0.4 for i in range(90)], index=idx)
        flat   = pd.Series([50.0] * 90, index=idx)

        sel_rising = select_forecaster(rising, 30)
        sel_flat   = select_forecaster(flat, 30)

        assert sel_rising is not None and sel_flat is not None
        avg_rising = sum(p.value for p in sel_rising.points) / 30
        avg_flat   = sum(p.value for p in sel_flat.points) / 30
        assert avg_rising > avg_flat, \
            "Rising CPU series should predict higher values than flat series"

    def test_falling_storage_predicts_lower_than_rising(self):
        idx = pd.date_range("2025-01-01", periods=90, freq="D")
        falling = pd.Series([80.0 - i * 0.3 for i in range(90)], index=idx)
        rising  = pd.Series([30.0 + i * 0.3 for i in range(90)], index=idx)

        sel_fall = select_forecaster(falling, 30)
        sel_rise = select_forecaster(rising, 30)
        assert sel_fall is not None and sel_rise is not None

        last_fall = sel_fall.points[-1].value
        last_rise = sel_rise.points[-1].value
        assert last_fall < last_rise, \
            "Falling series should end with lower predicted value than rising"

    def test_spike_in_history_widens_prediction_interval(self):
        idx_smooth = pd.date_range("2025-01-01", periods=60, freq="D")
        smooth = pd.Series([50.0 + i * 0.1 for i in range(60)], index=idx_smooth)

        idx_spike = pd.date_range("2025-01-01", periods=60, freq="D")
        vals_spike = [50.0 + i * 0.1 for i in range(60)]
        vals_spike[30] = 95.0   # sudden spike at day 30
        spiky = pd.Series(vals_spike, index=idx_spike)

        sel_smooth = select_forecaster(smooth, 30)
        sel_spiky  = select_forecaster(spiky, 30)

        assert sel_smooth is not None and sel_spiky is not None
        # Interval width at the last point
        width_smooth = sel_smooth.points[-1].upper - sel_smooth.points[-1].lower
        width_spiky  = sel_spiky.points[-1].upper  - sel_spiky.points[-1].lower
        assert width_spiky >= width_smooth, \
            "A history with a spike should produce a wider prediction interval"
