#!/usr/bin/env python3
"""Patch missing Server-Hall-B cooling links in the dual-DC topologies.

The cooling layer was generated by an external process that wired Server Hall A
but left Hall B's CRAH/CDU units with zero cooling links — so Hall B never
participates in the leak-heat / CHW-penalty cascade. This restores them,
mirroring the Hall A pattern, for every DC in each file:

  * each Hall B CRAH  -> the DC's CHW supply + return sensors
  * each Hall B CDU   -> the CHW sensors + 12 cold-plate servers from its own
                         rack (CDU in row R rack N cools Hall B row R rack N)

Idempotent: only adds links that don't already exist. Re-run safely.
"""
import json
import sys
from collections import defaultdict

# Only linked topologies (nodes + edges). The *_floorplan.json is a derived
# physical-layout view with no edges, so it has nothing to patch.
FILES = [
    "topologies/dual_dc_enterprise.json",
]
SERVERS_PER_CDU = 12


def patch(path: str) -> int:
    with open(path, encoding="utf-8") as fh:
        doc = json.load(fh)
    if "nodes" not in doc or "edges" not in doc:
        print(f"{path}: no nodes/edges (layout file), skipped")
        return 0
    nodes = {n["id"]: n["device"] for n in doc["nodes"]}
    edges = doc["edges"]

    def f(i, k, d=None):
        return nodes.get(i, {}).get(k, d)

    existing = {(e["src"], e["dst"]) for e in edges if e["layer"] == "cooling"}

    def has_cool(a, b):
        return (a, b) in existing or (b, a) in existing

    def add_cool(a, b):
        if has_cool(a, b):
            return 0
        edges.append({"src": a, "dst": b, "src_iface": 0,
                      "dst_iface": 0, "layer": "cooling"})
        existing.add((a, b))
        return 1

    # cooling-link degree (to find the orphaned Hall B units)
    cdeg = defaultdict(int)
    for e in edges:
        if e["layer"] == "cooling":
            cdeg[e["src"]] += 1
            cdeg[e["dst"]] += 1

    # servers already on a CDU cold-plate loop (skip when assigning)
    cooled = set()
    for e in edges:
        if e["layer"] != "cooling":
            continue
        for a, b in ((e["src"], e["dst"]), (e["dst"], e["src"])):
            if f(a, "device_type") == "cdu" and f(b, "device_type") == "server":
                cooled.add(b)

    added = 0
    dcs = sorted({f(i, "datacenter") for i in nodes if f(i, "datacenter")})
    for dc in dcs:
        chw = [i for i in nodes
               if f(i, "datacenter") == dc
               and ((f(i, "name") or "").endswith("-CHWS")
                    or (f(i, "name") or "").endswith("-CHWR"))]

        # Hall B CRAH → CHW sensors
        for i in nodes:
            if (f(i, "datacenter") == dc and f(i, "device_type") == "crah"
                    and f(i, "room") == "Server Hall B" and cdeg[i] == 0):
                for s in chw:
                    added += add_cool(i, s)

        # Hall B CDU → CHW sensors + 12 cold-plate servers from its own rack
        for i in nodes:
            if not (f(i, "datacenter") == dc and f(i, "device_type") == "cdu"
                    and f(i, "room") == "Server Hall B" and cdeg[i] == 0):
                continue
            for s in chw:
                added += add_cool(i, s)
            row, rack = f(i, "rack_row"), f(i, "rack_num")
            rack_srv = [j for j in nodes
                        if f(j, "device_type") == "server"
                        and f(j, "datacenter") == dc
                        and f(j, "room") == "Server Hall B"
                        and f(j, "rack_row") == row and f(j, "rack_num") == rack]
            # uncovered first, then stable by rack position/name
            rack_srv.sort(key=lambda j: (j in cooled,
                                         f(j, "rack_unit", 0) or 0,
                                         f(j, "name") or ""))
            for j in rack_srv[:SERVERS_PER_CDU]:
                added += add_cool(i, j)
                cooled.add(j)

    if added:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(doc, fh, indent=2)
    return added


def main():
    for path in FILES:
        try:
            n = patch(path)
            print(f"{path}: added {n} cooling edges")
        except FileNotFoundError:
            print(f"{path}: not found, skipped", file=sys.stderr)


if __name__ == "__main__":
    main()
